SAVE_GAME_TO_FILE = true
SAVE_FILE = "./data/savefile.txt"
# Directory for storing temporary files like an on-the-fly generated map file
TEMP_DIR = "./tmp/"
SAVE_MAP = "./tmp/_temp_map_file.csv"
LOAD_MAP = ""
PRINT_BOARD = false
MAX_TURNS = 1000
ASYNC = false

[LogSettings]
LOG_OUTPUT = "stderr"
LOG_LEVEL = "Info"

[GameSettings]
VICTORY_POINT_GOAL = 10
[GameSettings.DevCards]
KNIGHT = 14
ROAD_BUILDING = 2
YEAR_OF_PLENTY = 2
MONOPOLY = 2
VICTORY_POINT = 5
[GameSettings.MaxComponents]
CITY = 4
SETTLEMENT = 5
ROAD = 14
RESOURCE = 25

[PlayerSettings]
